version: "3.9"
services:
  app:
    image: hozakar/php-laravel
    container_name: myapp
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ${APP_ROOT}:/project

  db:
    image: mysql
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      # - /var/lib/mysql
      # if you want to mount mysql
      # to a specific directory on the host
      # use the one below
      - ${MYSQL_MOUNT:-./db_mount}:/var/lib/mysql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db

  jobs:
    restart: unless-stopped
    image: hozakar/jobber-curl
    container_name: jobs
    volumes:
      - ${JOBBER_FILE}:/home/jobberuser/.jobs
    depends_on:
      - app
